[default.databases.sqlite_logs]
url = "./database.sqlite"

[default]
upload_directory = "./upload"
id_length = 10
limits = { file = "15MiB", data-form = "15MiB"}
max_upload = 1500
cleaning_frequency = 1800
url = "./database.sqlite"
check_token = false
front_sources = "./front/dist"
default_duration = 9223372036854775806 # in seconds
